version: '3.7'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "index:app", "--conf", "gunicorn.conf.py"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    mem_limit: 1g
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
